authentik: 
  fullnameOverride: authentik

  replicas: 1

  worker:
    replicas: 1

  envValuefrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          key: authentik
          name: AUTHENTIK_SECRET_KEY
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          key: authentik
          name: auth-postgresql-user
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          key: authentik
          name: auth-postgresql-password
      AUTHENTIK_POSTGRESQL__PORT:
        secretKeyRef:
          key: authentik
          name: auth-postgresql-port

  env:
    AUTHENTIK_COOKIE_DOMAIN: robotwizard.co.uk

  authentik:

    # postgresql:
    #   host: authentik-database-rw
    redis:
      host: authentik-redis-master

  ingress:
    enabled: true
    
  postgresql:
    enabled: true
  # #    fullnameOverride: postgresql
  #   postgresqlUsername: "authentik"
  #   postgresqlDatabase: "authentik"
  #   persistence:
  #     enabled: true
  #     storageClass:
  #     accessModes:
  #       - ReadWriteOnce
  redis:
    enabled: true
  #    fullnameOverride: redis

  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10

  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
