---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 167.235.66.20/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: layer2advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - main-address-pool
  interfaces:
  - eth0
  # nodeSelectors:
  # - matchLabels:
  #     kubernetes.io/hostname: argocd