---
creation_rules:
  - path_regex: clusters/hetzner/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
        - age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
  - path_regex: manifests/.*
    encrypted_regex: "^(data|stringData)$"
    key_groups:
        - age:
          - age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
