---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/mattkgwhite/homeops.git"
    path: manifests/workloads/ci/tekton
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: utility
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true