controller:
  image: "jenkins/jenkins"
  tag: 2.402-jdk11
  tagLabel: jdk11
  imagePullPolicy: IfNotPresent
  numExecutors: 2
  admin:
    existingSecret: "jenkins"
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

ingress:
  enabled: false

agent:
  enabled: true
  image: "jenkins/inbound-agent"
  tag: "latest-jdk11"
