all:
  children:
    infrastructure:
      hosts:
        pve:
          ansible_host: proxmox.{{ansible_hostname}}
          fallback_ip: 192.168.1.10
          ansible_user: root
    operating_systems:
      hosts:
        ubuntu:
          ansible_host: ubuntu.{{ansible_hostname}}
          fallback_ip: 192.168.1.11
          ansible_user: {{ansible_user}}
    tools:
      children:
        argo:
          hosts:
            host1:
              ansible_host: argo.{{ansible_hostname}}
              fallback_ip: 192.168.1.12
              ansible_user: {{ansible_user}}
        flux:
          hosts:
            host2:
              ansible_host: flux.{{ansible_hostname}}
              fallback_ip: 192.168.1.13
              ansible_user: {{ansible_user}}
        docker:
          hosts:
            host3:
              ansible_host: docker.{{ansible_hostname}}
              fallback_ip: 192.168.1.14
              ansible_user: {{ansible_user}}