# apiVersion: v1
# kind: Namespace
# metadata:
#   name: argo-rollouts
# # ---
# # apiVersion: external-secrets.io/v1beta1
# # kind: ExternalSecret
# # metadata:
# #   name: sso
# #   namespace: argo-rollouts
# #   labels:
# #     app.kubernetes.io/part-of: argocd
# # spec:
# #   refreshInterval: "5m"
# #   secretStoreRef:
# #     kind: ClusterSecretStore
# #     name: 1password
# #   target:
# #     creationPolicy: Owner
# #   data:
# #     - secretKey: token
# #       remoteRef:
# #         key: sso
# #         property: workflows
# # ---
# # apiVersion: cert-manager.io/v1
# # kind: Certificate
# # metadata:
# #   name: workflows-cert
# # spec:
# #   commonName: workflows.<path:stringreplacesecret#domain>
# #   secretName: workflows-cert
# #   dnsNames:
# #     - workflows.<path:stringreplacesecret#domain>
# #   issuerRef:
# #     name: letsencrypt-production
# #     kind: ClusterIssuer
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: workflows-extname
# #   annotations:
# #     external-dns.alpha.kubernetes.io/hostname: workflows.<path:stringreplacesecret#domain>
# #     external-dns.alpha.kubernetes.io/ttl: "300"
# # spec:
# #   type: ExternalName
# #   externalName: nginx.<path:stringreplacesecret#domain>
# #   sessionAffinity: None
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-rollouts
#   namespace: argocd
# spec:
#   destination:
#     namespace: argo-rollouts
#     server: https://kubernetes.default.svc
#   project: homelab
#   source:
#     chart: argo-rollouts
#     repoURL: https://argoproj.github.io/argo-helm
#     targetRevision: 2.32.0
#     helm:
#       values: |
#         fullnameOverride: argo-rollouts
#   syncPolicy:
#     automated:
#       allowEmpty: true
#       prune: true
#       selfHeal: true
# # ---
# # apiVersion: networking.k8s.io/v1
# # kind: Ingress
# # metadata:
# #   name: argo-workflows
# #   namespace: argo-workflows
# #   annotations:
# #     cert-manager.io/cluster-issuer: letsencrypt-production
# #     kubernetes.io/ingress.class: nginx
# #     kubernetes.io/tls-acme: 'true'
# # spec:
# #   ingressClassName: nginx
# #   tls:
# #   - hosts:
# #     - workflows.<path:stringreplacesecret#domain>
# #     secretName: workflows-cert
# #   rules:
# #   - host: workflows.<path:stringreplacesecret#domain>
# #     http:
# #       paths:
# #       - backend:
# #           service:
# #             name: argo-workflows-server
# #             port:
# #               number: 2746
# #         path: /
# #         pathType: Prefix