addons:
  spc:
    enabled: true
    defaultObjectPath: k8s/external/aws
    objects:
      - name: credentials


cert-manager:
  fullnameOverride: cert-manager
  installCRDs: true
  webhook:
    enabled: false
  cainjector:
    replicaCount: 1
  extraArgs:
    - "--dns01-recursive-nameservers-only"
    - '--dns01-recursive-nameservers="8.8.8.8:53"'
  volumeMounts:
    - mountPath: /.aws
      name: aws-credentials
      readOnly: true