autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
  # rk1's run on 5.10 version of kernel, 5.12 is required
  bbr: false
bpf:
  masquerade: true
  # disable ebpf due to issues
  # https://github.com/cilium/cilium/issues/30510#issuecomment-1926155601
  # hostLegacyRouting: true
envoy:
  enabled: true
cluster:
  name: home-cluster
  id: 1
endpointRoutes:
  enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: "10.42.0.0/16"
k8sServiceHost: "192.168.1.75"
k8sServicePort: 6443
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
securityContext:
  privileged: true
routingMode: native
gatewayAPI:
  enabled: true
  externalTrafficPolicy: Local
  secretsNamespace:
    create: false
    name: certificate