all:
  vars:
    # ansible_user: automation
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    # ansible_become: true
  children:

    # proxmox:
    #   hosts:
    #     pve1:
    #       ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/proxmox') }}"
    #       ansible_user: root
    # docker:
    #   hosts:
    #     docker1:
    #       ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/docker') }}"
    # k3s:
    #   hosts:
    #     argo:
    #       ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/argo') }}"
    # discord:
    #   hosts:
    #     disco:
    #       ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/disco') }}"
    hetzner:
      hosts:
        chaos:
          ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/chaos')}}"
        hermes:
          ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/hermes')}}"
        # argo:
        #   ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/argo')}}"
        #viper:
        #  ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/viper') }}"
        # authentik:
        #   ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/authentik') }}"
        # docker:
        #   ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/docker') }}"
        # kubernetes:
        #   ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/kubernetes') }}"
        # db:
        #   ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/db') }}"
        # vps1:
        #   ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/vps1') }}"
        # vps2:
        #   ansible_host: "{{ lookup('pipe', 'op read op://homelab/ansible/vps2') }}"

    ubuntu:
      children:
        docker:
        k3s:
        discord:
        hetzner:

    # fedora:
      # children:
