# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:c2Al0aK4mj+WrDl6yCZSZy4=,iv:txqG3Y/kAv5mB3g+adPjRrmwgHM/yiwLV5IIexTSkOY=,tag:39XPegvFA++wYg12W6aH9Q==,type:str]
    SECRET_PUBLIC_DOMAIN2: ENC[AES256_GCM,data:HQBpvdG2hhITYQ==,iv:hRYebjyNKwARtyKmI1X2vZOTbEDOCXGmXyoNuKQ6/Us=,tag:RIUXJtS3EZnMXGPbWkNYKg==,type:str]
    SECRET_PUBLIC_DOMAIN3: ENC[AES256_GCM,data:tczD9yEKVqRf/TFBq7avjg==,iv:ZTF8utjyz0IvHPHMnDrVkRbPUxC0r0p/tZ5cyNZ8XuM=,tag:lF/1gS5D2Dy1EUnu9dVD6w==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:1R+AK87oTkCfsm/bOyK16QJtJvWe,iv:+EbaDjOBdsnrsrmWE8qNyoSVJE32nfTdlyjlkPbZLfA=,tag:WomAowfBMwbDBxTcNa9GNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYm5ocHZLaWxWZlFBZkV5
            UTZSYzErV2lUUVZIYW5vOVpwTUlzN1djdzNvCjhYdmlHU1NYcFB5VXhZMGk1c1V4
            Wko0cjFDRDQzVlVxWHBmZnpDckR3WG8KLS0tIHJKUmdKZk5VZEt4RmQ3MFJydGFO
            NG9qL1hrWndkQmR5eG1NUzVvNkplK1kKFpzmFYb85+98K3C+qA7pp3bCMj4tY7ST
            NOcIcD81gZ2zmEw0bOoJVInGuGhMuia56iiJlfbYEWDILi00x6d9ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-05T19:43:53Z"
    mac: ENC[AES256_GCM,data:l63JCeAQgRbn+mfQC+M/28iyPbV/1g0Ndnxu7RJW/appNOFV/WDwcCxhk8vRfEQwQkYW67+kZBDL/0Rvg9krEP4lv4W+W4n8MVp/MFDE0L4CgLXiKGMFXuus9HSGEul0yOrckApTHltGuzTxeUM+4frbi6znTFmSP+wrf0pVCR8=,iv:bvj127Qz1BmE8GkprxfclEMsA4cxunTvTj/oJcWHdVI=,tag:QYfWRD0yGXohPIfQUuq8Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
