---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-extname
  namespace: oidc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: keycloak.hacksm.net
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/instance: keycloak
spec:
  type: ExternalName
  externalName: nginx.hacksm.net
  sessionAffinity: None