kind: Namespace
apiVersion: v1
metadata:
  name: ingress-nginx-external
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-external
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx-external
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.7.1
    helm:
      values: |
        controller:
          service:
            enabled: true
            annotations:
              metallb.universe.tf/loadbalancerIPs: <path:stringreplacesecret#ip>"
            type: ClusterIP
          ingressClass: nginx
          ingressClassResource:
            name: ingress-nginx
            controllerValue: "k8s.io/ingress-nginx"
          admissionWebhooks:
            enabled: false
    # plugin:
    #   name: kustomize-inline
    #   env:
    #     - name: KUSTOMIZATION_YAML
    #       value: |
    #         apiVersion: v1
    #         kind: Service
    #         metadata:
    #           name: ingress-nginx-controller
    #           namespace: kube-system
    #         spec:
    #           loadBalancerClass: metallb
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true