apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: jenkins
  name: jenkins
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: sso
#   namespace: jenkins
# spec:
#   refreshInterval: "5m"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: 1password
#   target:
#     creationPolicy: Owner
#   data:
#     - secretKey: jenkins-admin-secret
#       remoteRef:
#         key: jenkins
#         property: admin-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins.<path:stringreplacesecret#domain>
    secretName: jenkins-cert
  rules:
  - host: jenkins.<path:stringreplacesecret#domain>
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-extname
  namespace: jenkins
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jenkins.<path:stringreplacesecret#domain>
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ExternalName
  externalName: nginx.<path:stringreplacesecret#domain>
  sessionAffinity: None
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: homelab
  source:
    # renovate: registryUrl=https://charts.jenkins.io
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 4.3.23
    helm:
      values: |
        fullnameOverride: jenkins
        controller:
          image: "jenkins/jenkins"
          tag: 2.330-jdk11
          tagLabel: jdk11
          imagePullPolicy: IfNotPresent
          numExecutors: 1
          # admin:
          #   existingSecret: "jenkins-admin-secret"
          #   userKey: 
          #   passwordKey: "jenkins"
        initializedOnce: true
        ingress:
          enabled: false
        podSecurityContextOVerride:
          runAsUser: 1000
          runAsNonRoot: false
          supplementGroups: [1000]
          capabilities: {}
        agent:
          enabled: true
          image: "jenkins/inbound-agent"
          tag: "4.11-1"
        persistence:
          jenkins-home:
            enabled:
            storageClass: hcloud-volume
            accessMode: ReadWriteOnce
            mountPath: /var/jenkins_home
            size: 20Gi
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true