apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: jenkins
  name: jenkins
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: sso
#   namespace: jenkins
# spec:
#   refreshInterval: "5m"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: 1password
#   target:
#     creationPolicy: Owner
#   data:
#     - secretKey: jenkins-admin-secret
#       remoteRef:
#         key: jenkins
#         property: admin-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins.<path:stringreplacesecret#domain>
    secretName: jenkins-cert
  rules:
  - host: jenkins.<path:stringreplacesecret#domain>
    http:
      paths:
      - backend:
          service:
            name: jenkins
            port:
              number: 8080
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-extname
  namespace: jenkins
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jenkins.<path:stringreplacesecret#domain>
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: ExternalName
  externalName: nginx.<path:stringreplacesecret#domain>
  sessionAffinity: None
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: jenkins
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/mattkgwhite/home-ops.git
      path: manifests/jenkins.yaml
      targetRevision: HEAD
    - chart: jenkins
      repoURL: https://charts.jenkins.io
      targetRevision: 4.6.4
      helm:
        values: |
          fullnameOverride: jenkins
          controller:
            image: "jenkins/jenkins"
            tagLabel: jdk11
            imagePullPolicy: IfNotPresent
            numExecutors: 1
            adminUser: "admin"
            # admin:
            #   existingSecret: "jenkins-admin-secret"
            #   userKey: 
            #   passwordKey: "jenkins"
          initializedOnce: true
          sidecars:
            configAutoReload:
              enabled: true
              image: kiwigrid/k8s-sidecar:1.24.4
              imagePullPolicy: IfNotPresent
          ingress:
            enabled: false
          podSecurityContextOVerride:
            runAsUser: 1000
            runAsNonRoot: false
            supplementGroups: [1000]
            capabilities: {}
          agent:
            enabled: true
            image: "jenkins/inbound-agent"
          persistence:
            enabled: true
            storageClass: hcloud-volume
            accessMode: "ReadWriteOnce"
            mountPath: /var/jenkins_home
            size: 20Gi
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true