kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.24.0
    helm:
      values: |
        fullnameOverride: kube-state-metrics
        releaseLabel: true # disable for victoria-metrics
        metricLabelsAllowlist:
          - deployments=[*]
          - persistentvolumeclaims=[*]
          - pods=[*]
        prometheus:
          monitor:
            enabled: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true