---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: monitoring
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  project: default
  source:
    chart: uptime-kuma
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 1.4.2
    helm:
      values: |
        nameOverride: uptime-kuma
        image:
          repository: louislam/uptime-kuma
          tag: 1.21.3
          pullPolicy: IfNotPresent
        env:
          TZ: Europe/London
        service:
          main:
            enabled: true
            type: ClusterIP
            ports:
              http:
                protocol: TCP
                port: 80
                targetPort: 3001
          # extname:
          #   # Broken in Chart v1.2.2, Common 4.5.2
          #   enabled: false
          #   type: ExternalName
          #   externalName: traefik.<path:stringreplacesecret#domain>
          #   annotations:
          #     external-dns.alpha.kubernetes.io/hostname: uptime.<path:stringreplacesecret#domain>
          #     external-dns.alpha.kubernetes.io/ttl: "300"
        ingress:
          main:
            enabled: false
        persistence:
          config:
            enabled: true
            mountPath: /app/data
            storageClass: hcloud-volume
            accessMode: ReadWriteMany
            size: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-cert
  namespace: monitoring
spec:
  commonName: uptime.<path:stringreplacesecret#domain>
  secretName: uptime-cert
  dnsNames:
    - uptime.<path:stringreplacesecret#domain>
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - uptime.<path:stringreplacesecret#domain>
    secretName: uptime-cert
  rules:
  - host: uptime.<path:stringreplacesecret#domain>
    http:
      paths:
      - backend:
          service:
            name: uptime-kuma
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: uptime.<path:stringreplacesecret#domain>
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/instance: uptime-kuma
spec:
  type: ExternalName
  externalName: nginx.<path:stringreplacesecret#domain>
  sessionAffinity: None