---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: sso
#   namespace: jenkins
# spec:
#   refreshInterval: "5m"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: 1password
#   target:
#     creationPolicy: Owner
#   data:
#     - secretKey: jenkins-admin-secret
#       remoteRef:
#         key: jenkins
#         property: admin-secret
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: vault-cert
#   namespace: vault
# spec:
#   commonName: vault.hacksm.net
#   secretName: vault-cert
#   dnsNames:
#     - vault.hacksm.net
#   issuerRef:
#     name: acme-prod
#     kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault
  annotations:
    cert-manager.io/cluster-issuer: acme-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vault.hacksm.net
    secretName: vault-cert
  rules:
  - host: vault.hacksm.net
    http:
      paths:
      - backend:
          service:
            name: vault
            port:
              number: 8200
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: vault-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vault.hacksm.net
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/instance: vault
spec:
  type: ExternalName
  externalName: nginx.hacksm.net
  sessionAffinity: None
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  project: homelab
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
    helm:
      values: |
        server:
          image:
            repository: "hashicorp/vault"
            tag: "1.14.0"
            pullPolicy: IfNotPresent
          ingress:
            enabled: false
          dataStorage:
            enabled: true
            storageClass: hcloud-volume
          dev:
            enabled: false
          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                # Enable unauthenticated metrics access (necessary for Prometheus Operator)
                #telemetry {
                #  unauthenticated_metrics_access = "true"
                #}
              }
              storage "file" {
                path = "/vault/data"
              }
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg