---
- name: Add SSH Key to Ubuntu Servers
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Add SSH public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAsampleexamplekey... your_ssh_key_here"