authentik: 
  fullnameOverride: authentik
  replicas: 1

  worker:
    replicas: 1

  envValuefrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik
          key: AUTHENTIK_SECRET_KEY
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: authentik
          key: AUTHENTIK_POSTGRESQL__USER
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: authentik
          key: AUTHENTIK_POSTGRESQL__PASSWORD
      AUTHENTIK_POSTGRESQL__PORT:
        secretKeyRef:
          name: authentik
          key: AUTHENTIK_POSTGRESQL__PORT

  env:
    AUTHENTIK_COOKIE_DOMAIN: hacksm.net

  authentik:
    # postgresql:
    #   host: authentik-database-rw
    redis:
      enabled: true
      host: authentik-redis-master

    ingress:
      enabled: true
      
    postgresql:
      enabled: true
    # #    fullnameOverride: postgresql
    #   postgresqlUsername: "authentik"
    #   postgresqlDatabase: "authentik"
    #   persistence:
    #     enabled: true
    #     storageClass:
    #     accessModes:
    #       - ReadWriteOnce
    
    # redis:
    #   enabled: true
  #    fullnameOverride: redis

    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10

    readinessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
