---
- name: Create a user on Ubuntu 24.04 LTS Server
  hosts: all  # Adjust this to target the correct group or hosts
  become: yes # Run tasks as sudo
  vars:
    username: "newuser"
    user_password: "{{ 'SuperSecurePassword' | password_hash('sha512') }}"
    ssh_key: "ssh-rsa AAAAB3Nza...your-public-key-here..."
  
  tasks:
    - name: Ensure the user exists
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: "/bin/bash"
        home: "/home/{{ username }}"
        createhome: yes
        groups: sudo  # Add to sudo group (optional)
        append: yes
    
    - name: Set up SSH key for the user
      authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_key }}"
        state: present
        manage_dir: yes
    
    - name: Ensure sudo access without password (optional)
      copy:
        dest: "/etc/sudoers.d/{{ username }}"
        content: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        mode: "0440"
      when: username != "root"



---
- name: Create a user on Ubuntu 24.04 LTS Server
  hosts: all  # Adjust this to target the correct group or hosts
  become: yes # Run tasks as sudo
  vars_files:
    - secrets.yml  # Encrypted file storing sensitive data

  tasks:
    - name: Ensure the user exists
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: "/bin/bash"
        home: "/home/{{ username }}"
        createhome: yes
        groups: sudo  # Add to sudo group (optional)
        append: yes
    
    - name: Set up SSH key for the user
      authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_key }}"
        state: present
        manage_dir: yes
    
    - name: Ensure sudo access without password (optional)
      copy:
        dest: "/etc/sudoers.d/{{ username }}"
        content: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        mode: "0440"
      when: username != "root"