---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mlohr-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://helm-charts.mlohr.com/
  timeout: 15m