apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
spec:
  acme:
    email: certificates@robotwizard.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - "matt-white.co.uk"
            - "robotwizard.co.uk"
        dns01:
          route53:
            region: us-east-1