---
apiVersion: v1
kind: Service
metadata:
  name: authentik-extname
  annotations:
    external-dns.alpha.kubernetes.io/hostname: authentik.robotwizard.co.uk
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app.kubernetes.io/instance: authentik
spec:
  type: ExternalName
  externalName: nginx.robotwizard.co.uk
  sessionAffinity: None