---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  METALLB_INGRESS_ADDR: ${METALLB_INGRESS_ADDR}
  SECRET_PUBLIC_DOMAIN: ${SECRET_PUBLIC_DOMAIN}
  SECRET_PUBLIC_DOMAIN2: ${SECRET_PUBLIC_DOMAIN2}
  SECRET_PUBLIC_DOMAIN3: ${SECRET_PUBLIC_DOMAIN2}
  SECRET_EMAIL: ${SECRET_EMAIL}