---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "excalidraw"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/mattkgwhite/home-ops.git"
    path: manifests/workloads/utility/excalidraw
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: excalidraw
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true