---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  #- ./authentication
  # - ./infrastructure
  - ./kube-tools
  #- ./monitoring
  # - ./system-upgrade