name: external-dns
apiVersion: v2
version: 1.0.0
dependencies:
  - name: ingress-nginx
    version: 4.4.2
    # renovatebot:alturl=https://kubernetes.github.io/ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx