---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
helmCharts:
  - name: external-dns
    releaseName: external-dns 
    namespace: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.14.4
    valuesFile: values.yaml

generators:
  - ksops-generator.yaml

resources:
  - ns.yaml