---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mattkgwhite-homeops
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/mattkgwhite/home-ops.git
  ref:
    branch: main
  # secretRef:
  # name: github-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/hetzner/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: mattkgwhite-home-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age