# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:XPfI/hz3fDY1GvUn3oX1HvV1goduFLzDgLGXCmXJa6Xkild4TNDItw==,iv:7WDkfTY4iircDzuKP/0pgtAHRU6uxWfKbqV24HCtcLo=,tag:h/0pW9XyatJ4aLnIdcJpXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h4cpc8tl30e9ye50zh3y2al8jh4nfgr4gj6k9v26jegyzd7ez5sq8mns5h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeHE3OEJHQVh6Ty9vVmNC
        TjJxUHVoZmhTSHNLMy85aDY0aGsreWFoVWhnCmErV2MvQ21RMzZtb25IMFd6M0VL
        bjlxdGhTQUJxMGtDS25lTCthbVRob0kKLS0tIDVyMW01TEUzb0wweWNrV0YrVVBh
        SjJNOWd2UlNXbFFoajhOSVNRQzJYYVUKuxd5m0UZayu2PKCA0HijxQaVC4f7WiFc
        A1/iih2Fo+QQV/I3JlxbtCHzJZq6mBdtgkLvs4QE3Ti5KfVhE9RpgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-14T20:45:34Z"
  mac: ENC[AES256_GCM,data:FdHZ0lUZzQiQqAJh9mQ/tz3Lu4VP+eaHqZSACOK6fHReWmcNRxl76gqjF8m21V0K+OP11GgHU5osB2dntPElQdQJqCwJcl8/+08/OUUZA7qSpLh9gj2Fl739SiwSWjCx8HRilD8a/RVhCMURHghYVHM/vJxWcvpAKhWhkOAUnKE=,iv:gFGaii2WkryMphhyQEtpOgKuS5zV6KuVRVErzsC+cYU=,tag:dNviQhJQhQTVbr+NvYiEJw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
