apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-cert
spec:
  secretName: jenkins-cert
  dnsNames:
  - jenkins.<path:stringreplacesecret#domain>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer