# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: gateway
# spec:
#   # controllerName: hacksm.net/metallb-controller
#   gatewayClassName: prod
#   listeners:
#   - name: http
#     port: 80
#     protocol: HTTP
#     hostname: "nginx.hacksm.net"
#   - name: https
#     port: 443
#     protocol: HTTPS
#     hostname: "nginx.hacksm.net"
#     tls:
#       mode: Terminate
#       certificateRefs:
#       - kind: Secret
#         name: letsencrypt-production
#   - name: https-default-tls-mode
#     port: 8443
#     protocol: HTTPS
#     hostname: "nginx.hacksm.net"
#     tls:
#       certificateRefs:
#       - kind: Secret
#         name: letsencrypt-production

# # ---
# # kind: Namespace
# # apiVersion: v1
# # metadata:
# #   name: gateway
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: external
# spec:
#   gatewayClassName: metallb
#   listeners:
#   - protocol: HTTP
#     port: 80
#     name: http
#     # allowedRoutes:
#     #   namespaces:
#     #     from: All
#   - protocol: HTTPS
#     port: 443
#     name: https
#     tls:
#       certificateRefs:
#         - kind: Secret
#           name: letsencrypt-production
#           namespace: cert-manager
#       # allowRoutes:
#       #   namespaces:
#       #     from: All
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: httpsredirect-externalgw
#   namespace: gateway
# spec:
#   parentRefs:
#     - name: external
#       namespace: gateway
#       sectionName: http
#   rules:
#     - filters:
#         - requestRedirect:
#             scheme: https
#             statusCode: 301
#           type: RequestRedirect
# ---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: extgw
#   namespace: gateway
#   # annotations:
#   #   external-dns.custom/type: public
# spec:
#   endpoints:
#     - dnsName: extgw.hacksm.net
#       recordType: CNAME
#       targets:
#         - "nginx.hacksm.net"
#       providerSpecific:
#         - name: external-dns.alpha.kubernetes.io/hostname
#           value: nginx.hacksm.net