# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: vault
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: "https://github.com/mattkgwhite/homeops.git"
#     path: manifests/workloads/vault
#     targetRevision: main
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: vault
#   syncPolicy:
#     automated:
#       prune: true
#     syncOptions:
#       - CreateNamespace=true