# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: vault-cert
# spec:
#   commonName: vault.robotwizard.co.uk
#   secretName: vault-cert
#   dnsNames:
#     - vault.robotwizard.co.uk
#   issuerRef:
#     name: acme-prod
#     kind: ClusterIssuer
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: vault-robotwizard-co-uk-web
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`vault.robotwizard.co.uk`)
#       kind: Rule
#       services:
#         - name: vault
#           port: 80
#       middlewares:
#         - name: http-https-redirectscheme
#           namespace: kube-system
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: vault-robotwizard-co-uk-websecure
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`vault.robotwizard.co.uk`)
#       kind: Rule
#       services:
#         - name: vault
#           port: 80
#   tls:
#     secretName: vault