# vault:
#   server:
#     image:
#       repository: "hashicorp/vault"
#       tag: "1.12.4"
#       pullPolicy: IfNotPresent
#     ingress:
#       enabled: true
#     dataStorage:
#       enabled: true
#       storageClass: hcloud-volumes
#     dev:
#       enabled: false
#     standalone:
#       enabled: false
#     ha:
#       enabled: false
#       replicas: 1
#       raft:
#         enabled: true
#         setNodeId: true
#     ui:
#       enabled: true
#       serviceType: "Loadbalancer"
#     csi:
#       enabled: true
#     injector:
#       enabled: true
#     resources:
#         requests:
#           memory: 256Mi
#           cpu: 250m
#         limits:
#           memory: 256Mi
#     readinessProbe:
#       enabled: true
#       path: "/v1/sys/health?sealedcode=204&uninitcode=204"
#       failureThreshold: 2
#       initialDelaySeconds: 10
#       periodSeconds: 5
#       successThreshold: 1
#       timeoutSeconds:
#     livenessProbe:
#       failureThreshold: 2
#       initialDelaySeconds: 5
#       periodSeconds: 5
#       successThreshold: 1
#       timeoutSeconds: 3
#     extraSecretEnvironmentVars: []
#       - envName: AWS_ACCESS_KEY_ID
#         secretName: aws-creds
#         secretKey: AWS_ACCESS_KEY_ID
#       - envName: AWS_SECRET_ACCESS_KEY
#         secretName: aws-creds
#         secretKey: AWS_SECRET_ACCESS_KEY
