---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./external-dns
  #- ./hcloud-csi-driver
  - ./ingress-nginx
  # - ./kyverno
  - ./metallb
  # - ./tekton
  # - ./vault
  # - ./vault-secrets-operator
