---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

helmCharts:
  - name: vault
    releaseName: vault
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.23.0
    valuesFile: values.yaml