vault:
  server:
    image:
      repository: "vault"
      tag: "1.12.3"
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: acme-prod
      hosts:
        - host: kube-vault.robotwizard.co.uk
          paths: [/]
      tls:
        - hosts: [kube-vault.robotwizard.co.uk]
          secretName: kube-vault-robotwizard-co-uk
  dataStorage:
    storageClass: nfs-client
  ui:
    enabled: true
    serviceType: "ClusterIP"
  csi:
    enabled: true
  injector:
    enabled: true
  resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 256Mi
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?sealedcode=204&uninitcode=204"
