---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - letsencrypt-production.yaml
  - https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.crds.yaml