---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-issuers
  namespace: &namespace kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: *namespace
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-production
        spec:
          acme:
            server: https://acme-v02.api.letsencrypt.org/directory
            email: "${SECRET_EMAIL}"
            privateKeySecretRef:
              name: letsencrypt-production
            solvers:
              - selector:
                  dnsZonesSecretRef:
                    name: r53-dns-zones
                    key: dns-zones
                dns01:
                  route53:
                    region: us-east-1
                    accessKeyIDSecretRef:
                      name: r53-access-key-id  
                      key: access-key-id
                    secretAccessKeySecretRef:
                      name: r53-secret-access-key 
                      key: secret-access-key
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-staging
        spec:
          acme:
            server: https://acme-staging-v02.api.letsencrypt.org/directory
            email: "${SECRET_EMAIL}"
            privateKeySecretRef:
              name: letsencrypt-staging
            solvers:
              - selector:
                  dnsZonesSecretRef:
                    name: r53-dns-zones
                    key: dns-zones
                dns01:
                  route53:
                    region: us-east-1
                    accessKeyIDSecretRef:
                      name: r53-access-key-id  
                      key: access-key-id
                    secretAccessKeySecretRef:
                      name: r53-secret-access-key 
                      key: secret-access-key