---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: flux-installation
    - name: flux-cluster
  path: ./k8s/clusters/hetzner/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: mattkgwhite-homeops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings