---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-csi-driver
  namespace: utility
spec:
  interval: 5m
  chart:
    spec:
      chart: hcloud-csi-driver
      version: 1.0.4
      sourceRef:
        kind: HelmRepository
        name: mlohr-charts
        namespace: flux-system
      interval: 5m