# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cifs-data-pv
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 100Gi
#   flexVolume:
#     driver: juliohm/cifs
#     options:
#       server: change-me-to-storage-server-name
#       share: /backup
#     secretRef:
#       name: cifs
#       namespace: kube-system
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cifs-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""