---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-cert
  namespace: jenkins
spec:
  commonName: jenkins.robotwizard.co.uk
  secretName: jenkins-cert
  dnsNames:
    - jenkins.robotwizard.co.uk
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    cert-manager.io/cluster-issuer: acme-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins.robotwizard.co.uk
    secretName: jenkins-cert
  rules:
  - host: jenkins.robotwizard.co.uk
    http:
      paths:
      - backend:
          service:
            name: jenkins
            port:
              number: 8200
        path: /
        pathType: Prefix