---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utility

resources:
  - ns.yaml
  - rbac.yaml
  - ingress.yaml

helmCharts:
  - name: kah-common-chart
    releaseName: jenkins
    namespace: utility
    repo: https://k8s-at-home.com/charts
    version: 1.2.2
    valuesFile: values.yaml

images:
  - name: jenkins-container-image
    newName: docker.io/jenkins/jenkins
    newTag: 2.387.2-lts