# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: vault-config
# data:
#   config: |
#     ui = true
#     disable_mlock = true
#     listener "tcp" {
#       tls_disable = 1
#       address = "[::]:8200"
#       cluster_address = "[::]:8201"
#     }
#     storage "raft" {
#       path = "/vault/data"
#     }
#     api_addr = "http://0.0.0.0:8200"
#     service_registration "kubernetes" {}