apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name 1passwordconnect
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Helm Repo Ref
  - repoURL: https://github.com/mattkgwhite/home-ops.git
    targetRevision: main
    ref: values
    # Helm Chart Deployment
  - repoURL: https://1password.github.io/connect-helm-charts
    chart: *name
    targetRevision: 1.14.0
    helm:
      valueFiles:
      - $values/kubernetes/core/1passwordconnect/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
