apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name gateway
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Helm Repo Ref
  - repoURL: https://github.com/mattkgwhite/home-ops.git
    targetRevision: main
    ref: values
    # Helm Chart Deployment
  - repoURL: https://kubernetes-sigs.github.io/gateway/
    chart: *name
    # targetRevision: 1.13.1
    helm:
      valueFiles:
      - $values/kubernetes/core/gateway/crds.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
