apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name hcloud-csi
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Helm Repo Ref
  - repoURL: https://github.com/mattkgwhite/home-ops.git
    targetRevision: main
    ref: values
    # Helm Chart Deployment
  - repoURL: https://helm-charts.mlohr.com/
    chart: *name
    targetRevision: 2.6.0
    helm:
      valueFiles:
      - $values/kubernetes/core/hcloud-csi/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
