apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name kong
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Git Repo Deployment
  - path: kubernetes/core/kong
    repoURL: &repo https://github.com/mattkgwhite/home-ops.git
    targetRevision: &targetRev main
  # Helm Repo Ref
  - repoURL: *repo
    targetRevision: *targetRev
    ref: values
  # Helm Chart Deployment
  - repoURL: https://charts.konghq.com
    chart: *name
    targetRevision: 2.38.0
    helm:
      valueFiles:
      - $values/kubernetes/core/kong/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
