apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name metallb
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  # Helm Repo Ref
  - repoURL: https://github.com/mattkgwhite/home-ops.git
    targetRevision: main
    ref: values
    # Helm Chart Deployment
  - repoURL: https://metallb.github.io/metallb
    chart: *name
    targetRevision: 0.14.4
    helm:
      valueFiles:
      - $values/kubernetes/core/metallb/values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
