# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: &name vault
#   namespace: argocd
# spec:
#   destination:
#     namespace: argocd
#     server: https://kubernetes.default.svc
#   project: default
#   sources:
#   # Helm Repo Ref
#   - repoURL: https://github.com/mattkgwhite/home-ops.git
#     targetRevision: main
#     ref: values
#     # Helm Chart Deployment
#   - repoURL: https://argoproj.github.io/argo-helm
#     chart: *name
#     targetRevision: 5.51.2
#     helm:
#       valueFiles:
#       - $values/kubernetes/core/argocd/values.yaml
#   syncPolicy:
#     automated:
#       prune: true
#     syncOptions:
#     - CreateNamespace=true
#     - ServerSideApply=true
