---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

helmCharts:
  - name: authentik
    releaseName: authentik
    namespace: authentik
    repo: https://charts.goauthentik.io
    version: 2023.5.3
    # valuesFile: values.yaml

generators:
  - ksops-generator.yaml

resources:
  - ns.yaml
  - ingress.yaml
  - service.yaml
  - argocd-application.yaml
