kind: Namespace
apiVersion: v1
metadata:
  name: envoy-gateway
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  destination:
    namespace: envoy-gateway
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: mirror.gcr.io/envoyproxy
    chart: gateway-helm
    targetRevision: v1.8.0
    helm:
      skipCrds: true
      valuesObject:
        global:
          imageRegistry: mirror.gcr.io
        config:
          envoyGateway:
            provider:
              type: Kubernetes
              kubernetes:
                deploy:
                  type: GatewayNamespace
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true