# ---
# kind: Namespace
# apiVersion: v1
# metadata:
#   name: postgres
# ---
# apiVersion: acid.zalan.do/v1
# kind: postgresql
# metadata:
#   name: cluster01
#   namespace: postgres
# spec:
#   teamId: acid
#   volume:
#     size: 5Gi
#     storageClass: hetzner-storagebox
#   numberOfInstances: 2
#   preparedDatabases:
#     # mealie:
#     #   defaultUsers: true
#     #   extensions: {}
#     #   schemas:
#     #     data:
#     #       defaultRoles: false
#     #       defaultUsers: false
#     # miniflux:
#     #   defaultUsers: true
#     #   extensions: {}
#     #   schemas:
#     #     data:
#     #       defaultRoles: false
#     #       defaultUsers: false
#     vikunja:
#       defaultUsers: true
#       extensions: {}
#       schemas:
#         # still uses public schema...
#         # https://community.vikunja.io/t/postgres-database-has-error-pq-relation-tasks-does-not-exist/1333
#         public:
#           defaultRoles: false
#           defaultUsers: false
#   postgresql:
#     version: "17"
#     parameters:
#       password_encryption: scram-sha-256
# ---
# apiVersion: external-secrets.io/v1alpha1
# kind: PushSecret
# metadata:
#   name: cluster01.vikunja.owner
#   namespace: postgres
#   annotations:
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# spec:
#   refreshInterval: "5m"
#   secretStoreRefs:
#     - name: 1password
#       kind: ClusterSecretStore
#   selector:
#     secret:
#       name: vikunja-owner-user.cluster01.credentials.postgresql.acid.zalan.do
#   data:
#     - match:
#         secretKey: username
#         remoteRef:
#           remoteKey: postgres.cluster01.vikunja.owner
#           property: username
#     - match:
#         secretKey: password
#         remoteRef:
#           remoteKey: postgres.cluster01.vikunja.owner
#           property: password