apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secrets
    namespace: kube-system
stringData:
    access-key-id: ENC[AES256_GCM,data:uH8baWROu0cZ5Pc4yyOr+S2cfWg=,iv:HqGkjfTOOlKUSyhahu3nDncvp52Z5YYBMvWlNcUVsmo=,tag:3rWKZDqe629tOBoDWzGrug==,type:str]
    secret-access-key: ENC[AES256_GCM,data:J7JrbxohWYmKvDV9JsnT2Gpn7shjnR4nR2iVswz8l7JVGSgSAftWZQ==,iv:gUWJEzqcv2lD2fKGjtPjNlojFU7MAmTeIt3fFpR0wgU=,tag:0k4ZeSkmaSbNbX/SHfRvBw==,type:str]
    dns-zones: ENC[AES256_GCM,data:pT16bYUpfsJaX6jbiooegeTUDZHsJu13KzOisHojQEOvSQ==,iv:ycnQU5opMJ8Wyk7CTZR/rAeLEHx4F1rStYtqST7RGdo=,tag:ornsh6Gd2KY7tDDjSEtGjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ytjlx50szj2283j7vacf9ezhrct2mcfcjmqqjgqa37eqhcgt853s8mmlwu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUFluZjVucjk5K3VVbWlZ
            Z3lvMHdEaEcyYlpMRDhSRDBsc2RKaGtHanprCndvWTlJQk8vZVZqYmpTYUFvaDBW
            ejE0ckl2T0dVL1M1T3hlYnFMMG1ibVUKLS0tIENOLzFPZ0hvL3JNOGlBS2U2Ui9J
            WFVIS1Y1eHNiMDJZazNKL1NuT3BnL2cKs4X7iYSIwKJvZfLMDUdoMFNfEbZu5ZQK
            LrlABy4+yupd/bsaaWSQk/j31VLLX3nTjNQnRkDum2xLBYm33+1A9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-08T23:20:47Z"
    mac: ENC[AES256_GCM,data:M0rOqwb6v4txoPCEEIim6L41k16Fp/1PKaZ6v8DUmwNX1dOpQB6mH9tfw74SnFCnRFPvfdo5QTUkDHh7VkQ5g8Y04fZurqfGVNafGNiGlf449pZWBvwZRiMcUx50zTHwvRjX6epMBVcHFP1BvrUeLHuwe7aVsmNJ4JAqeJPV9eA=,iv:T97UWQJhC9e9UPEcR0oiJIcsTY0vTtRwmKZ7w2udVHo=,tag:fIAfBpiNLXFURz/fe2+JyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
