---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultConnection
metadata:
  namespace: vault-connection
  name: vault-connection
spec:
  # required configuration
  # address to the Vault server.
  address: "http://vault:8200"
