---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: cert-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-access-key
      remoteRef:
        key: aws
        property: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIAW4YYMLNFKAG25JMV
          secretAccessKeySecretRef:
            name: cert-manager-secret
            key: secret-access-key
      selector:
        dnsZones:
          - 'hacksm.net'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIAW4YYMLNFKAG25JMV
          secretAccessKeySecretRef:
            name: cert-manager-secret
            key: secret-access-key
      selector:
        dnsZones:
          - 'hacksm.net'