---
- name: Retrieve SSH Key from 1Password and Add to Server
  hosts: ubuntu_servers
  become: true
  vars_prompt:
    - name: op_email
      prompt: "Enter your 1Password email"
      private: no
    - name: op_password
      prompt: "Enter your 1Password password"
      private: yes

  tasks:
    - name: Authenticate with 1Password and generate session token
      command: >
        op signin myvault "{{ op_email }}" "{{ op_password }}" --raw
      register: op_session_result

    - name: Set 1Password session variable
      set_fact:
        op_session: "{{ op_session_result.stdout }}"

    - name: Fetch SSH Key from 1Password
      command: >
        op item get "My SSH Key" --vault myvault --fields "publicKey" --session "{{ op_session }}"
      register: ssh_key_output

    - name: Extract Public Key
      set_fact:
        ssh_public_key: "{{ ssh_key_output.stdout }}"

    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Add SSH public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_public_key }}"